# Generated by Django 2.2.3 on 2019-08-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190806_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='delegation_contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
