# Generated by Django 2.2.3 on 2019-08-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delegation_delegation_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chair',
        ),
    ]
