# Generated by Django 2.2.3 on 2019-08-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_chair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegation',
            old_name='delegation_contact_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='delegation',
            old_name='delegation_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='delegation',
            old_name='delegation_size',
            new_name='size',
        ),
    ]
