# Generated by Django 2.2.3 on 2019-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190818_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
