# Generated by Django 2.2.3 on 2019-08-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegation', '0003_auto_20190808_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delegation.Committee')),
            ],
        ),
    ]
