# Generated by Django 2.2.3 on 2019-08-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delegation', '0003_auto_20190808_0913'),
        ('secretariat', '0003_auto_20190809_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delegation.Committee')),
            ],
        ),
    ]
