# Generated by Django 2.2.3 on 2019-08-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0006_chair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsrequest',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delegation.Committee'),
        ),
    ]
