# Generated by Django 2.2.3 on 2019-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0007_auto_20190812_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresssheet',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
