# Generated by Django 2.2.3 on 2019-08-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0008_auto_20190814_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
    ]
