# Generated by Django 2.2.7 on 2019-11-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0010_auto_20191119_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
