# Generated by Django 2.2.3 on 2019-08-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20190806_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_first_name', models.CharField(max_length=200)),
                ('delegate_last_name', models.CharField(max_length=200)),
                ('delegate_email', models.EmailField(max_length=254)),
                ('delegate_dob', models.DateField(null=True)),
                ('delegate_past_conferences', models.IntegerField(null=True)),
                ('delegate_committee_preference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delegation.Committee')),
                ('delegate_country_preference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delegation.Country')),
                ('delegate_delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Delegation')),
            ],
        ),
        migrations.CreateModel(
            name='CountryCommitteeAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_committee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delegation.Committee')),
                ('allocated_country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delegation.Country')),
                ('allocated_delegate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delegation.Delegate')),
            ],
            options={
                'unique_together': {('allocated_country', 'allocated_committee')},
            },
        ),
        migrations.AddField(
            model_name='country',
            name='country_committee',
            field=models.ManyToManyField(through='delegation.CountryCommitteeAllocation', to='delegation.Committee'),
        ),
    ]
