# Generated by Django 2.2.3 on 2019-08-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0002_auto_20190808_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='committee',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
    ]
