# Generated by Django 2.2.3 on 2019-08-18 10:46

from django.db import migrations
from django.db.migrations.operations import RenameModel

class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0005_positionpaper'),
    ]

    operations = [
        RenameModel(old_name='CountryCommitteeAllocation', new_name='Allocation'),
    ]
