# Generated by Django 2.2.3 on 2019-08-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0006_auto_20190818_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='allocated_delegate',
            new_name='delegate',
        ),
    ]
