# Generated by Django 2.2.3 on 2019-08-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0007_auto_20190818_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='allocated_committee',
            new_name='committee',
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='allocated_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_last_name',
            new_name='last_name',
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('country', 'committee')},
        ),
    ]
