# Generated by Django 2.2.3 on 2019-08-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0008_auto_20190818_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_committee_preference',
            new_name='committee_preference',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_country_preference',
            new_name='country_preference',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_delegation',
            new_name='delegation',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='delegate_past_conferences',
            new_name='past_conferences',
        ),
    ]
