# Generated by Django 2.2.3 on 2019-08-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0009_auto_20190818_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_committee',
            new_name='committee',
        ),
    ]
